updated for 12.04 (start of)

diff --git a/tstools_package/ts_reset_panel b/tstools_package/ts_reset_panel
--- a/tstools_package/ts_reset_panel
+++ b/tstools_package/ts_reset_panel
@@ -10,8 +10,8 @@ help(){
                                  externally mounted  drive 
 
 
-	Resets gnome panels to their default state. 
-        Currently obsolete. Works only with Ubuntu 10.04
+	Resets xfce panels to their default state. 
+        Only works with Xubuntu 12.04
 EOF
 }
 
@@ -40,34 +40,28 @@ done
 
 #set/check user
 if [[ -z $user ]]; then
-        user=$USER
+    user=$USER
 elif ! test_for_root; then
 	echo "Could not proceed"
-      	echo "are you root?"
-       	exit 3
+    echo "are you root?"
+    exit 3
 elif ! test_for_user $user $path; then
-       	echo "$user not found! exiting..."
-       	exit 3
+    echo "$user not found! exiting..."
+   	exit 3
 fi
+
+pgrep xfce4 >> /dev/null
+if [[ $? ==  0 && $user  == $USER]]; then
+    echo "You can not run this program if you are logged in as the user"
+    echo "you are attempting to change while xfce4 (the graphic environment"
+    echo " is running"
+    exit 4 
+if
 
 # reset panel second stage maybe unnecessary need to test
 
 # set appropriate command and options
-if ! reset_gconf $user /apps/panel $path; then
-	echo "gconf failed to reset panel" 
-	exit 3
-fi
-#if ! rm -rf /home/$user/.gconf/apps/panel; then
-#        echo "gconf failed to remove /home/$user/.gconf/apps/panel" 
-#        exit 3
-#fi
-
-if [[ ! $path ]] ; then
-	if ! pkill gnome-panel ; then
-        	echo "failed to restart gnome-panel" 
-        	exit 2
-	fi
-else
-	exit 0
-fi
  
+
+# see ticket #32682
+
